# myFile=open("hello.txt","w")
# myFile.write("ICTA Calicut Full Stack Class")
# myFile.close()
# print("File generated Succesfully")
myFile=open("hello.txt","r")
s=myFile.read()
print(s)
myFile.close()
